describe("package", function()
   it("exposes the engine facade", function()
      local engine = require("engine")
      assert.are.equal("Tumble Lab", engine.version.name)
      assert.is_function(engine.World.new)
      assert.is_function(engine.Body.new)
      assert.is_function(engine.collide.collide)
      assert.is_function(engine.solver.solve)
      assert.is_function(engine.shape.circle)
   end)
end)
